/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.HouseholdManagerFrame;

import controllers.HoKhauManagerController.ChangeListPeopleController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import bean.MemOfFamily;
import java.awt.Color;
import java.awt.Font;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.BevelBorder;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.ActionEvent;
import javax.swing.JPanel;

/**
 *
 * @author Hai
 */
public class ChangeListPeopleJframe extends javax.swing.JFrame {

    /**
     *     public ChangeListPeopleController(List<MemOfFamily> listMember, JButton addBtn, JButton removeBtn, JTextField searchJtf, JPanel peopleJpn, JPanel memJpn) {
     */
    private List<MemOfFamily> listMember;
    private List<MemOfFamily> listMemberTemp;
    private ChangeListPeopleController controller;
    private JFrame parentJframe;
    
    /**
     * Creates new form ChangeListPeopleJframe
     * @param listMember
     * @param parentJFrame
     */
    public ChangeListPeopleJframe(List<MemOfFamily> listMember, JFrame parentJFrame) {
        initComponents();
        this.listMember = listMember;
        this.listMemberTemp = new ArrayList<>();
        this.listMemberTemp.addAll(listMember);
        this.parentJframe = parentJFrame;
        this.controller = new ChangeListPeopleController(this.listMemberTemp, addBtn, removeBtn, searchJtf, PeopleTableJpn, MemTableJpn);
        MemTableJpn.setLayout(null);
        PeopleTableJpn.setLayout(null);
        this.parentJframe.setEnabled(false);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                close();
            }
            
        });
    }
    private void close() {
        if (JOptionPane.showConfirmDialog(this, "Are you sure to close??", "Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            this.parentJframe.setEnabled(true);
            dispose();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        
        JPanel Jpanel1 = new JPanel();
        Jpanel1.setBackground(new Color(230, 230, 250));

   
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(Jpanel1, GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(Jpanel1, GroupLayout.PREFERRED_SIZE, 582, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(63, Short.MAX_VALUE))
        );
        Jpanel1.setLayout(null);
        searchJtf = new javax.swing.JTextField();
        searchJtf.setBounds(64, 26, 432, 30);
        searchJtf.setForeground(new Color(255, 255, 255));
		searchJtf.addFocusListener(new FocusListener() {
		    @Override
		    public void focusGained(FocusEvent e) {
		        if (searchJtf.getText().equals("Search")) {
		        	searchJtf.setText("");
		        	searchJtf.setForeground(Color.BLACK);
		        }
		    }
		    @Override
		    public void focusLost(FocusEvent e) {
		        if (searchJtf.getText().isEmpty()) {
		        	searchJtf.setForeground(Color.GRAY);
		        	searchJtf.setText("Search");
		        }
		    }
		    });
		searchJtf.setSelectionColor(new Color(255, 255, 255));
		searchJtf.setFont(new Font("Tahoma", Font.PLAIN, 15));
		searchJtf.setBorder(new CompoundBorder(new BevelBorder(BevelBorder.LOWERED, new Color(153, 102, 255), null, null, null), new EmptyBorder(0, 10, 0, 0)));
		//searchJtf.setBounds(247, 12, 200, 50);
		//jPanel1.add(searchJtf);
		searchJtf.setColumns(10);
        Jpanel1.add(searchJtf);
        
        searchJtf.setFont(new java.awt.Font("Tohama", 1, 15));
                PeopleTableJpn = new javax.swing.JPanel();
                PeopleTableJpn.setBounds(24, 93, 424, 400);
                Jpanel1.add(PeopleTableJpn);
                PeopleTableJpn.setBackground(new Color(255, 255, 255));
                
                addBtn = new javax.swing.JButton();
                addBtn.setBounds(474, 93, 51, 25);
                Jpanel1.add(addBtn);
                addBtn.setText(">>");
                addBtn.setForeground(Color.WHITE);
                addBtn.setBorderPainted(false);
                addBtn.setBorder(new LineBorder(new Color(186, 85, 211), 1, true));
                addBtn.setFont(new Font("Tahoma", Font.BOLD, 15));
                addBtn.setForeground(new Color(255, 255, 255));
                addBtn.setBackground(new Color(147, 112, 219));
                addBtn.addActionListener(new ActionListener() {
                	public void actionPerformed(ActionEvent e) {
                	}
                });
                
                        addBtn.setFont(new java.awt.Font("Tohama", 1, 15)); // NOI18N
                        addBtn.setText(">>");
                        
                        
                        removeBtn = new javax.swing.JButton();
                        removeBtn.setBounds(474, 154, 51, 25);
                        Jpanel1.add(removeBtn);
                        removeBtn.setText("<<");
                        removeBtn.setForeground(Color.WHITE);
                        removeBtn.setFont(new Font("Tahoma", Font.BOLD, 15));
                        removeBtn.setBorderPainted(false);
                        removeBtn.setBorder(new LineBorder(new Color(186, 85, 211), 1, true));
                        removeBtn.setBackground(new Color(147, 112, 219));
                        removeBtn.addActionListener(new ActionListener() {
                        	public void actionPerformed(ActionEvent e) {
                        	}
                        });
                        
                                removeBtn.setFont(new java.awt.Font("Tohama", 1, 15)); // NOI18N
                                removeBtn.setText("<<");
                                saveBtn = new javax.swing.JButton();
                                saveBtn.setBounds(812, 26, 113, 30);
                                Jpanel1.add(saveBtn);
                                saveBtn.setForeground(Color.WHITE);
                                saveBtn.setBorderPainted(false);
                                saveBtn.setBorder(new LineBorder(new Color(186, 85, 211), 1, true));
                                saveBtn.setBackground(new Color(147, 112, 219));
                                saveBtn.setFont(new Font("Tahoma", Font.BOLD, 15)); // NOI18N
                                saveBtn.setText("Lưu thay đổi");
                                MemTableJpn = new javax.swing.JPanel();
                                MemTableJpn.setBounds(563, 93, 402, 400);
                                Jpanel1.add(MemTableJpn);
                                MemTableJpn.setBackground(new Color(255, 255, 255));
                                saveBtn.addActionListener(new java.awt.event.ActionListener() {
                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        saveBtnActionPerformed(evt);
                                    }
                                });
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        this.listMember.clear();
        this.listMember.addAll(this.listMemberTemp);
        NewHouseholdFrame themMoiHoKhau = (NewHouseholdFrame)this.parentJframe;
        themMoiHoKhau.setDataThanhVien();
        close();
    }//GEN-LAST:event_saveBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MemTableJpn;
    private javax.swing.JPanel PeopleTableJpn;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField searchJtf;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton saveBtn;
}
