/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.HoKhauManagerFrame;

import controllers.HoKhauManagerController.TachHoKhauController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

import javax.swing.JPanel;
import java.awt.Color;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;

import javax.swing.GroupLayout;

import javax.swing.JButton;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.border.BevelBorder;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author User
 */
public class HouseholdSeper1 extends javax.swing.JFrame {

    private TachHoKhauController controller;
    private JFrame parentJFrame;
    /**
     * Creates new form TachHoKhau
     * @param parentJFrame
     */
    public HouseholdSeper1(JFrame parentJFrame) {
    	getContentPane().setBackground(new Color(255, 255, 255));
        initComponents();
        this.parentJFrame = parentJFrame;
        controller = new TachHoKhauController(this);
        controller.setAcceptBtn(acceptBtn);
        controller.setAddBtn(addBtn);
        controller.setCancelBtn(cancelBtn);
        controller.setChuHoHienTaiJtf(chuHoHienTaiJtf);
        controller.setChuHoMoiJtf(chuHoMoiJtf);
        controller.setDiaChiJtf(diaChiJtf);
        controller.setMaHoKhauMoiJtf(maHoKhauMoiJtf);
        controller.setMaKhuVucJtf(maKhuVucJtf);
        jPanel1.setLayout(null);
        jPanel1.add(jLabel4);
        jPanel1.add(jLabel5);
        jPanel1.add(jLabel13);
        jPanel1.add(jLabel14);
        jPanel1.add(jLabel16);
        jPanel1.add(chuHoMoiJtf);
        jPanel1.add(maKhuVucJtf);
        jPanel1.add(diaChiJtf);
        jPanel1.add(maHoKhauMoiJtf);
        jPanel1.add(chuHoHienTaiJtf);
        jPanel1.add(jLabel6);
        jPanel1.add(jLabel7);
        jPanel1.add(jLabel12);
        jPanel1.add(jLabel15);
        jPanel1.add(jLabel17);
        controller.setSearchJtf(jtfSearch);
        jPanel2.setLayout(null);
        jPanel2.add(tableBotJpn);
        jPanel2.add(tableTopJpn);
        tableTopJpn.setLayout(null);
        jPanel2.add(jLabel18);
        jPanel2.add(jLabel1);
        jPanel2.add(removeBtn);
        jPanel2.add(tableRigthJtf);
        jPanel2.add(jPanel1);
        jPanel2.add(jLabel3);
        jPanel2.add(jLabel2);
        jPanel2.add(jtfSearch);
        jPanel2.add(cancelBtn);
        jPanel2.add(acceptBtn);
        jPanel2.add(addBtn);
        controller.init();
        this.setTitle("Tách hộ khẩu");
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                close(); //To change body of generated methods, choose Tools | Templates.
            }
            
        });
    }

    public void close() {
        if (JOptionPane.OK_OPTION == JOptionPane.showConfirmDialog(null, "Are you sure to close?", "Warning!!", JOptionPane.YES_NO_OPTION)) {
            this.parentJFrame.setEnabled(true);
            dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBounds(559, 103, 582, 252);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setBounds(10, 30, 123, 30);
        chuHoHienTaiJtf = new javax.swing.JTextField();
        chuHoHienTaiJtf.setBounds(158, 30, 386, 30);
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setBounds(10, 185, 93, 30);
        chuHoMoiJtf = new javax.swing.JTextField();
        chuHoMoiJtf.setBounds(158, 187, 386, 30);
        chuHoMoiJtf.setBackground(new Color(255, 255, 255));
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setBounds(548, 31, 19, 30);
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setBounds(548, 186, 19, 30);
        jLabel12 = new javax.swing.JLabel();
        jLabel12.setBounds(548, 70, 19, 30);
        jLabel13 = new javax.swing.JLabel();
        jLabel13.setBounds(9, 70, 94, 28);
        maKhuVucJtf = new javax.swing.JTextField();
        maKhuVucJtf.setBounds(158, 71, 386, 30);
        jLabel14 = new javax.swing.JLabel();
        jLabel14.setBounds(10, 108, 55, 30);
        diaChiJtf = new javax.swing.JTextField();
        diaChiJtf.setBounds(158, 110, 386, 30);
        jLabel15 = new javax.swing.JLabel();
        jLabel15.setBounds(548, 109, 19, 30);
        jLabel16 = new javax.swing.JLabel();
        jLabel16.setBounds(10, 148, 130, 30);
        maHoKhauMoiJtf = new javax.swing.JTextField();
        maHoKhauMoiJtf.setBounds(158, 148, 386, 30);
        jLabel17 = new javax.swing.JLabel();
        jLabel17.setBounds(548, 149, 19, 30);
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setBounds(24, 60, 183, 30);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setBounds(46, 10, 191, 30);
        jtfSearch = new javax.swing.JTextField("Search");
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setBackground(new Color(255, 255, 255));
        jLabel3.setBounds(641, 380, 240, 30);
        jLabel18 = new javax.swing.JLabel();
        jLabel18.setBounds(24, 380, 213, 30);
        jLabel18.setBackground(new Color(255, 255, 255));
        jLabel18.setForeground(new Color(0, 0, 0));
        addBtn = new javax.swing.JButton();
        addBtn.setFont(new Font("Tahoma", Font.BOLD, 15));
        acceptBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(230, 230, 250));

        jPanel1.setBackground(new java.awt.Color(240, 248, 255));

        jLabel4.setFont(new Font("Tahoma", Font.PLAIN, 18)); // NOI18N
        jLabel4.setText("Chủ hộ hiện tại");

        chuHoHienTaiJtf.setBackground(new Color(255, 255, 255));
        chuHoHienTaiJtf.setFont(new Font("Tahoma", Font.BOLD, 15)); // NOI18N

        jLabel5.setFont(new Font("Tahoma", Font.PLAIN, 18)); // NOI18N
        jLabel5.setText("Chủ hộ mới");

        chuHoMoiJtf.setFont(new Font("Tahoma", Font.BOLD, 15)); // NOI18N
        chuHoMoiJtf.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("(*)");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("(*)");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("(*)");

        jLabel13.setFont(new Font("Tahoma", Font.PLAIN, 18)); // NOI18N
        jLabel13.setText("Mã khu vực");

        maKhuVucJtf.setFont(new Font("Tahoma", Font.BOLD, 15)); // NOI18N

        jLabel14.setFont(new Font("Tahoma", Font.PLAIN, 18)); // NOI18N
        jLabel14.setText("Địa chỉ");

        diaChiJtf.setFont(new Font("Tahoma", Font.BOLD, 15)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("(*)");

        jLabel16.setFont(new Font("Tahoma", Font.PLAIN, 18)); // NOI18N
        jLabel16.setText("Mã hộ khẩu mới");

        maHoKhauMoiJtf.setFont(new Font("Tahoma", Font.BOLD, 15)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("(*)");

        jLabel1.setFont(new Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel1.setText("Chọn hộ cần tách");

        jLabel2.setFont(new Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel2.setText("Nhập mã hộ khẩu");
      //  jLabel2.setForeground(new Color(255, 255, 255));


        //jtfSearch.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
 
//        jtfSearch.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jtfSearchActionPerformed(evt);
//            }
//        });

		jtfSearch.setForeground(Color.GRAY);
		jtfSearch.addFocusListener(new FocusListener() {
		    @Override
		    public void focusGained(FocusEvent e) {
		        if (jtfSearch.getText().equals("Search")) {
		        	jtfSearch.setText("");
		        	jtfSearch.setForeground(Color.BLACK);
		        }
		    }
		    @Override
		    public void focusLost(FocusEvent e) {
		        if (jtfSearch.getText().isEmpty()) {
		        	jtfSearch.setForeground(Color.GRAY);
		        	jtfSearch.setText("Search");
		        }
		    }
		    });
		jtfSearch.setSelectionColor(new Color(204, 153, 255));
		jtfSearch.setFont(new Font("Tahoma", Font.PLAIN, 15));
		jtfSearch.setBorder(new CompoundBorder(new BevelBorder(BevelBorder.LOWERED, new Color(153, 102, 255), null, null, null), new EmptyBorder(0, 10, 0, 0)));
		jtfSearch.setBounds(247, 12, 866, 30);
		//panel_1.add(jtfSearch);
		jtfSearch.setColumns(10);

        jLabel3.setFont(new Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel3.setText("Chọn người sang hộ mới");

        jLabel18.setFont(new Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel18.setText("Những người ở hộ mới");

        addBtn.setText(">>");
        addBtn.setBorderPainted(false);
        addBtn.setBounds(531, 438, 60, 21);
        addBtn.setBorder(new LineBorder(new Color(186, 85, 211), 1, true));
        addBtn.setFont(new Font("Tahoma", Font.BOLD, 15));
        addBtn.setForeground(new Color(255, 255, 255));
        addBtn.setBackground(new Color(147, 112, 219));

        acceptBtn.setText("Xác nhận");
        acceptBtn.setBorderPainted(false);
        acceptBtn.setBounds(983, 708, 100, 25);
        acceptBtn.setBorder(new LineBorder(new Color(186, 85, 211), 1, true));
        acceptBtn.setFont(new Font("Tahoma", Font.BOLD, 15));
        acceptBtn.setForeground(new Color(255, 255, 255));
        acceptBtn.setBackground(new Color(147, 112, 219));
        
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Hủy");
        cancelBtn.setBorderPainted(false);
        cancelBtn.setBounds(850, 708, 100, 25);
        cancelBtn.setBorder(new LineBorder(new Color(186, 85, 211), 1, true));
        cancelBtn.setFont(new Font("Tahoma", Font.BOLD, 15));
        cancelBtn.setForeground(new Color(255, 255, 255));
        cancelBtn.setBackground(new Color(147, 112, 219));
        
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        
        removeBtn = new JButton();
        removeBtn.setBounds(531, 485, 60, 21);
        removeBtn.setText("<<");
        removeBtn.setForeground(Color.WHITE);
        removeBtn.setFont(new Font("Tahoma", Font.BOLD, 15));
        removeBtn.setBorderPainted(false);
        removeBtn.setBorder(new LineBorder(new Color(186, 85, 211), 1, true));
        removeBtn.setBackground(new Color(147, 112, 219));
        
        tableTopJpn = new JPanel();
        tableTopJpn.setBounds(24, 103, 469, 252);
        tableTopJpn.setBackground(new Color(255, 255, 255));
        tableTopJpn.setLayout(null);
        
        tableBotJpn = new JPanel();
        tableBotJpn.setBounds(24, 420, 469, 252);
        tableBotJpn.setBackground(new Color(255, 255, 255));
        
        tableRigthJtf = new JPanel();
        tableRigthJtf.setBackground(new Color(255, 255, 255));
        tableRigthJtf.setBounds(641, 420, 500, 252);
        tableRigthJtf.setLayout(null);
        tableBotJpn.setLayout(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addGap(25)
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 1167, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 756, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(89, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        close();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acceptBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField chuHoHienTaiJtf;
    private javax.swing.JTextField chuHoMoiJtf;
    private javax.swing.JTextField diaChiJtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField maHoKhauMoiJtf;
    private javax.swing.JTextField maKhuVucJtf;
    private javax.swing.JTextField jtfSearch;
    private JButton removeBtn;
    private JPanel tableTopJpn;
    private JPanel tableBotJpn;
    private JPanel tableRigthJtf;
    // End of variables declaration//GEN-END:variables

    public JFrame getParentJFrame() {
        return parentJFrame;
    }
}
